version: 1
formatters:
    default:
        {'format': '[%(asctime)s] [%(levelname)8s] --- %(message)s (%(filename)s:%(lineno)s)', 'datefmt': '%Y-%m-%d %H:%M:%S'}
handlers:
    console:
        level: 'DEBUG'
        class: 'logging.StreamHandler'
        formatter: 'default'
        stream: 'ext://sys.stdout'
    file:
        level: 'DEBUG'
        class: 'logging.handlers.RotatingFileHandler'
        formatter: 'default'
        filename: '.\logs\test.log'
        maxBytes: 1024
        backupCount: 5
loggers:
    default:
        level: 'DEBUG'
        handlers: ['console', 'file']


disable_existing_loggers': False
